name: 'Colvin Deploy NodeJs Projects'
description: 'Deploy Colvin NodeJs projects to Google Cloud'
runs:
  using: "composite"
  steps:
    - name: "Set ENV variables"
      run: |
        if [ ${GITHUB_REF##*/} == "master" ]; then
            if [ $DEPLOY_STAGE1 ]; then
                echo "STAGE=stage1" >> $GITHUB_ENV
                echo "BRANCH=stage1" >> $GITHUB_ENV
            else
                echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
            fi
        else
            echo "STAGE=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
            echo "BRANCH=volatile" >> $GITHUB_ENV
        fi
      shell: bash

    - name: "Validating environments"
      run: |
        REGEX="^stage[1-$LIMIT_STG]{1}$"
        if [[ ! $STAGE =~ $REGEX ]] && [ "$BRANCH" != "master" ]; then echo "ERROR: not allowed environment"; exit 1; fi
      shell: bash
      
    - name: "Get kubernetes credentials"
      run: |
        if [ $BRANCH == "master" ]; then
            gcloud container clusters get-credentials colvin --region $GCP_REGION
        else
            gcloud container clusters get-credentials stage --zone $GCP_ZONE
            if [ `kubectl get nodes -o json | jq '.items | length'` -eq 0 ]; then echo "ERROR: stage is stopped. Remember to start it!"; exit 1; fi
        fi
      shell: bash
      
    - name: "Decrypt terraform encrypted values"
      run: if [ -f "./terraform/variables-encrypted.tf.enc" ]; then sops -d terraform/variables-encrypted.tf.enc > terraform/variables-encrypted.tf; fi
      shell: bash
      
    - name: "Terraform Init"
      run: if [ -d "./terraform" ]; then terraform init -backend-config="credentials=`echo $SA_GCP`" -backend-config="prefix=`echo $APP_NAME`" -input=false terraform/; fi
      shell: bash

    - name: "Terraform Workspace"
      run: |
        if [ $BRANCH == "master" ]; then
            if [ -d "./terraform" ]; then terraform workspace select colvin terraform/ || terraform workspace new colvin terraform/; fi
        else
            if [ -d "./terraform" ]; then terraform workspace select $STAGE terraform/ || terraform workspace new $STAGE terraform/; fi
        fi
      shell: bash

    - name: "Terraform Plan"
      run: if [ -d "./terraform" ]; then terraform plan -var="client_secret=`echo $SA_GCP`" -var="app_name=`echo $APP_NAME`" terraform/; fi
      shell: bash

    - name: "Terraform Apply"
      run: if [ -d "./terraform" ]; then terraform apply -var="client_secret=`echo $SA_GCP`" -var="app_name=`echo $APP_NAME`" -auto-approve terraform/; fi
      shell: bash

    - name: "Get latest tag and auto increment version"
      run: |
        if [ $BRANCH == "master" ]; then
            LAST=`gcloud container images list-tags $REGISTRY --sort-by="TAGS" --filter="tags~^[0-9]" | sed '/TIMESTAMP/d' | sort -rVk2 | head -n1 | awk '{print $2}'`
            REGEX="([0-9]+).([0-9]+)"
        else
            MAJOR_VERSION="s"$MAJOR_VERSION
            LAST=`gcloud container images list-tags $REGISTRY --sort-by="TAGS" --filter="tags~^s[0-9]" | sed '/TIMESTAMP/d' | sort -rVk2 | head -n1 | awk '{print $2}'`
            REGEX="(s[0-9]+).([0-9]+)"
        fi
        if [[ $LAST =~ $REGEX ]]; then MAJOR="${BASH_REMATCH[1]}"; MINOR="${BASH_REMATCH[2]}"; fi
        if [ -z $MAJOR ]; then MAJOR="1"; MINOR="0"; fi
        if [ $MAJOR_VERSION != $MAJOR ]; then MAJOR=$MAJOR_VERSION; MINOR="1"; else MINOR=$(echo $MINOR + 1 | bc); fi
        echo "TAG_IMG=$MAJOR.$MINOR" >> $GITHUB_ENV
      shell: bash

    - name: "Build docker images"
      run: |
        export CONTAINER_IMAGE="$REGISTRY:$TAG_IMG"
        if [ $BRANCH == "master" ]; then
            docker-compose -f docker-compose.yml build --build-arg ENV_FILE_PATH=.env.production $CONTAINER_NAME
        else
            docker-compose -f docker-compose.yml build --build-arg ENV_FILE_PATH=.env.$STAGE $CONTAINER_NAME
        fi
      shell: bash

    - name: "Configure docker-cli to push images in GCR"
      run: gcloud auth configure-docker
      shell: bash

    - name: "Push docker images to GCR"
      run: docker push $REGISTRY:$TAG_IMG
      shell: bash

    - name: "Replace server version in helm values.yaml"
      run: sed -i "s/TAG_IMG/$TAG_IMG/g" ./helm/values.yaml
      shell: bash

    - name: "Install Helm secrets plugin"
      run: helm plugin install https://github.com/jkroepke/helm-secrets --version v3.5.0
      shell: bash

    - name: "Helm dependencies update"
      run: helm dependency update ./helm/
      shell: bash

    - name: "Deploy Helm"
      run: |
        if [ $BRANCH == "master" ]; then
            helm secrets upgrade $APP_NAME ./helm/ --install --wait --atomic -f ./helm/values.yaml -f ./helm/values.prod.yaml -f ./helm/secrets.yaml -f ./helm/secrets.prod.yaml
        else
            NUMSTG=`echo $STAGE | awk -F"stage" '{ print $2 }'`
            helm secrets upgrade ${APP_NAME}${NUMSTG} ./helm/ --install --wait --atomic -f ./helm/values.yaml -f ./helm/values.$STAGE.yaml -f ./helm/secrets.yaml -f ./helm/secrets.$STAGE.yaml
        fi
      shell: bash
